apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-db
spec:
  serviceName: timescale-db
  selector:
    matchLabels:
      io.kompose.service: timescale-db
  volumeClaimTemplates:
  - metadata:
      name: timescale-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gp3
      resources:
        requests:
          storage: 50Gi
  template:
    metadata:
      labels:
        io.kompose.service: timescale-db
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: timescale-db
          image: timescale/timescaledb-ha:pg17.5-ts2.20.1
          imagePullPolicy: Always 
          resources:
            requests:
              cpu: "3"
            limits:
              cpu: "3"
          ports:
          - containerPort: 5432
            protocol: TCP
          volumeMounts:
          - name: timescale-db-data
            mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_SHARED_PRELOAD_LIBRARIES
            value: "ai"
          - name: PGDATA
            value: "/var/lib/postgresql/data/pgdata"
      
      
