apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: raw-logs
  name: raw-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
