apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: hasura-migrations
  name: hasura-migrations
spec:
  initContainers:
    - name: wait
      image: busybox
      command: ['sh', '-c', 'sleep 5']
      volumeMounts:
        - name: aws-iam-token
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
          readOnly: true
        - name: kube-api-access-lc4b9
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
  serviceAccountName: secrets-access-sa
  containers:
    - image: ghcr.io/0xintuition/hasura-migrations:latest
      name: hasura-migrations
  volumes:
    - name: aws-iam-token
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 86400
    - name: kube-api-access-lc4b9
      projected:
        sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 3600
  restartPolicy: Never

