apiVersion: v1
kind: Service
metadata:
  name: graphql-engine
  labels:
    io.kompose.service: graphql-engine
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    io.kompose.service: graphql-engine