apiVersion: v1
kind: Service
metadata:
  name: graphql-engine
  labels:
    io.kompose.service: graphql-engine
spec:
  type: ClusterIP  # This is where 'type' should go
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    io.kompose.service: graphql-engine