functions:
  - function:
      name: share_price_changed_by_term_curve_id
      schema: public
    configuration:
      exposed_as: query
      arguments:
        - name: curve_id
          type: numeric
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_pnl_leaderboard
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_account_pnl_rank
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_pnl_leaderboard_stats
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_vault_leaderboard
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_pnl_leaderboard_period
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true
  - function:
      name: get_vault_leaderboard_period
      schema: public
    configuration:
      exposed_as: query
    permissions:
      - role: anonymous
        definition:
          allow: true
      - role: frontend
        definition:
          allow: true