FROM ubuntu:latest

# Install build essentials and git
RUN apt-get update && apt-get install -y \
    postgresql-client \
    jq \
    build-essential \
    git \
    curl \
    software-properties-common \
    libc6 \
    libstdc++6 \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# Install Foundry
RUN curl -L https://foundry.paradigm.xyz | bash && \
    /root/.foundry/bin/foundryup

# Add Foundry to PATH
ENV PATH="/root/.foundry/bin:${PATH}"

WORKDIR /app

# Copy the pre-cloned repository
COPY intuition-contracts-v2 .
RUN npm install
RUN forge build --via-ir --optimize

# Create a script to run the forge command
RUN echo '#!/bin/sh\n\
OUTPUT=$(forge script script/DeployV2ToGeth.s.sol --via-ir --optimize --rpc-url http://geth:8545 --keystore /data/keystore.json --password-file /data/password.txt --broadcast 2>&1)\n\
echo "$OUTPUT"\n\
MULTIVAULT_ADDRESS=$(echo "$OUTPUT" | grep "MultiVault proxy address:" | sed -E "s/.*MultiVault proxy address:[[:space:]]+//")\n\
PGPASSWORD=$POSTGRES_PASSWORD psql -h database -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT -c "UPDATE histocrawler.app_config SET contract_address = '\''$MULTIVAULT_ADDRESS'\'', start_block = 0 WHERE indexer_schema = '\''histo_base_sepolia_1_5'\''"' > /app/deploy.sh && chmod +x /app/deploy.sh

RUN echo '#!/bin/sh\n\
forge script script/DeployV2ToGeth.s.sol --via-ir --optimize --rpc-url http://geth:8545 --keystore /data/keystore.json --password-file /data/password.txt --broadcast --resume --verify --verifier blockscout --verifier-url http://host.docker.internal/api/\n' > /app/verify.sh && chmod +x /app/verify.sh

# Set the entrypoint to the script
ENTRYPOINT ["/app/deploy.sh"]