apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: raw-consumer
  name: raw-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: raw-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: raw-consumer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - ./consumer
            - --mode
            - raw
          name: raw-consumer
          ports:
            - containerPort: 8003
              protocol: TCP
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          envFrom: []
      restartPolicy: Always
