apiVersion: apps/v1
kind: Deployment
metadata:
  name: envio-indexer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: envio-indexer
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: dev-envio-indexer-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dev-base-sepolia-dev-envio-indexer-aws-secrets"