apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - base/aws-secrets/secrets-store.yaml
  - base/aws-secrets/service-account.yaml
  - base/namespaces.yaml
  - consumers/decoded
  - consumers/ipfs-upload
  - consumers/raw
  - consumers/resolver-consumer
  - ipfs
  - monitoring/log-cleanup
  - monitoring/prometheus
  - rbac/secrets-store-csi-driver-rbac.yaml
  - services/database
  - services/graphql
  - services/safe-content
  - services/sqs
  - substreams-sink

commonLabels:
  app: intuition