apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: database
    spec:
      containers:
        - env:
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_USER
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: PG_HOST
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready
            failureThreshold: 10
            periodSeconds: 1
            timeoutSeconds: 5
          name: database
          ports:
            - containerPort: 5435
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-data
          args:
            - -c
            - listen_addresses=*
      restartPolicy: Always
      volumes:
        - name: database-data
          persistentVolumeClaim:
            claimName: database-data
