apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoded-consumer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: decoded-consumer
          image: ghcr.io/0xintuition/consumer:2.0.21
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "3" 
              memory: "4Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-linea-mainnet-v2-decoded-consumer-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-linea-mainnet-v2-prod-linea-mainnet-v2-decoded-consumer-secrets"
