apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/decoded
  - secret-provider.yaml

namePrefix: "prod-linea-mainnet-v2-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: decoded-consumer

commonLabels:
  network: linea-mainnet-v2