apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-secrets-manager-csi-provider
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: aws-secrets-manager-csi-provider
  template:
    metadata:
      labels:
        app: aws-secrets-manager-csi-provider
    spec:
      serviceAccountName: secrets-store-csi-driver
      containers:
        - name: provider
          image: public.ecr.aws/aws-secrets-manager/secrets-store-csi-driver-provider-aws:1.0.r2-6-gee95299-2023.04.12.21.52
          imagePullPolicy: Always
          args:
            - --provider-volume=/etc/kubernetes/secrets-store-csi-providers
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          volumeMounts:
            - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
              name: providervol
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
