[workspace]
resolver = "2"
members = ["apps/cli", "apps/tui", "apps/consumer", "apps/histocrawler", "apps/image-guard", "apps/models", "apps/rpc-proxy", "apps/shared-utils"]


[workspace.dependencies]
alloy = { version = "1.0.32", features = ["full"] }
alloy-network = "1.0.32"
anyhow = "1.0.82"
async-trait = "0.1.83"
bytes = "1.8.0"
chrono = { version = "0.4.35", features = ["serde"] }
clap = { version = "4.5.20", features = ["derive"] }
dotenvy = "0.15.7"
envy = "0.4.2"
env_logger = "0.11.5"
hex = { version = "0.4.3", features = ["serde"] }
hypersync-client = "0.18.3"
log = "0.4.20"
macon = "1.2.0"
rand = "0.9.1"
reqwest = { version = "0.12.8", features = ["multipart", "json"] }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.8.6", features = [
    "postgres",
    "runtime-tokio",
    "uuid",
    "chrono",
    "bigdecimal",
    "rust_decimal",
    "tls-rustls"
] }
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.3"
tokio = { version = "1.20.1", features = ["full"] }
utoipa = { version = "5.2.0", features = ["macros", "axum_extras", "chrono"] }
url = "2.4.1"

