[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
default_to_workspace = false

[tasks]

# Docker tasks
[[extend]]
path = ".cargo/makefiles/docker.toml"

# Consumers tasks
[[extend]]
path = ".cargo/makefiles/consumers.toml"

# Development tasks
[[extend]]
path = ".cargo/makefiles/development.toml"
