[config]
default_to_workspace = false

# Run the RAW SQS consumer connected to the test queue in test mode
[tasks.raw-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--features",
    "local",
    "--",
    "--mode",
    "raw",
]

# Run the DECODED SQS consumer connected to the test queue in test mode
[tasks.decoded-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--features",
    "local",
    "--",
    "--mode",
    "decoded",
]

# Run the RESOLVER SQS consumer connected to the test queue in test mode
[tasks.resolver-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--features",
    "local",
    "--",
    "--mode",
    "resolver",
]

# Remove docker volumes
[tasks.remove-docker-volumes]
command = "docker"
args = ["compose", "down", "-v"]

# Start the docker compose stack
[tasks.start-docker]
command = "docker"
args = ["compose", "up", "-d", "--force-recreate"]

# Migrate the database
[tasks.migrate-database]
command = "hasura"
args = ["deploy", "--project", "hasura"]

# This task remove the docker volumes, start the docker compose stack, and migrate the database
[tasks.start-docker-and-migrate]
dependencies = ["remove-docker-volumes", "build-docker", "start-docker", "migrate-database"]

# Run the RAW SQS consumer connected to the real SQS queue
[tasks.raw-consumer]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "raw",
]

# Run the SQS consumer connected to the real SQS queue
[tasks.decoded-consumer]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "decoded",
]

# Run the SQS consumer connected to the real SQS queue
[tasks.resolver-consumer]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "resolver",
]

# Build the docker image for the consumer service
[tasks.build-docker]
command = "docker"
args = ["build", "-t", "consumer:latest", "-f", "consumer/Dockerfile", "."]


# Simply format and lint checking with `cargo clippy` for all targets
# in the workspace, promoting `warnings` to `errors`
[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--workspace", "--", "-Dwarnings"]