services:

  - type: web
    name: hasura
    runtime: image
    image:
      url: docker.io/hasura/graphql-engine:v2.44.0
    dockerCommand: graphql-engine serve --server-port $PORT
    plan: starter
    envVars:
    - key: HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES
      value: true
    - key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
      value: anonymous
    - key: HASURA_GRAPHQL_ADMIN_SECRET
      sync: false
    - key: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: true
    - key: PINATA_AUTH
      sync: false
    - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
      fromDatabase:
        name: database
        property: connectionString
    region: oregon
    healthCheckPath: /healthz
    autoDeploy: false

  ############################################################
  # Resolver Consumer
  ############################################################
  - type: worker
    plan: starter
    name: resolver-consumer
    runtime: image
    image:
      url: docker.io/leboiko/intuition-be:0.2.0 
    dockerCommand: ./consumer --mode resolver
    envVars:
      - key: CONSUMER_TYPE
        value: sqs
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: ENS_CONTRACT_ADDRESS
        value: 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e
      - key: IMAGE_GUARD_URL
        value: http://image-guard:3000
      - key: IPFS_UPLOAD_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/ipfs_upload
      - key: RESOLVER_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/resolver
      - key: RUST_LOG
        value: info
      - fromGroup: aws-credentials
      - fromGroup: pinata-secrets
      - fromGroup: rpc-mainnet
      - fromGroup: ipfs

  ############################################################
  # IPFS Upload Consumer
  ############################################################
  - type: worker
    plan: starter
    name: ipfs-upload-consumer
    runtime: image
    image:
      url: docker.io/leboiko/intuition-be:0.2.0 
    dockerCommand: ./consumer --mode ipfs-upload
    envVars:
      - key: CONSUMER_TYPE
        value: sqs
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: IMAGE_GUARD_URL
        value: http://image-guard:3000
      - key: IPFS_UPLOAD_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/ipfs_upload
      - key: RUST_LOG
        value: info
      - fromGroup: aws-credentials
      - fromGroup: pinata-secrets
      - fromGroup: ipfs

  ############################################################
  # Decoded Consumer
  ############################################################
  - type: worker
    name: decoded-consumer
    runtime: image
    image:
      url: docker.io/leboiko/intuition-be:0.2.0
    dockerCommand: ./consumer --mode decoded
    envVars:
      - key: CONSUMER_METRICS_API_PORT
        value: 3002
      - key: CONSUMER_TYPE
        value: sqs
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: DECODED_LOGS_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/decoded_logs
      - key: INTUITION_CONTRACT_ADDRESS
        value: 430BbF52503Bd4801E51182f4cB9f8F534225DE5
      - key: RUST_LOG
        value: info
      - fromGroup: aws-credentials
      - fromGroup: pinata-secrets

  ############################################################
  # Raw Consumer
  ############################################################
  - type: worker
    name: raw-consumer
    runtime: image
    image:
      url: docker.io/leboiko/intuition-be:0.2.0
    dockerCommand: ./consumer --mode raw
    envVars:
      - key: CONSUMER_TYPE
        value: sqs
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: DECODED_LOGS_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/decoded_logs
      - key: INDEXING_SOURCE
        value: substreams
      - key: RAW_CONSUMER_QUEUE_URL
        value: https://sqs.us-west-2.amazonaws.com/064662847354/raw_logs
      - key: RUST_LOG
        value: info
      - fromGroup: aws-credentials
      - fromGroup: pinata-secrets
      - fromGroup: rpc-mainnet
      - fromGroup: ipfs

  ############################################################
  # IPFS
  ############################################################
  # - type: web
  #   name: ipfs
  #   runtime: image
  #   image:
  #     url: ipfs/kubo:latest
  #   dockerCommand: |
  #     sh -c "
  #     if [ ! -f /data/ipfs/config ]; then
  #       ipfs init;
  #     fi;
  #     ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001;
  #     ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080;
  #     ipfs pin remote service add Pinata https://api.pinata.cloud/psa $PINATA_API_JWT;
  #     ipfs config --json Gateway.PublicGateways '{\"localhost\": {\"UseSubdomains\": false,\"Paths\": [\"/ipfs\", \"/ipns\"]},\"ipfs\": {\"UseSubdomains\": false,\"Paths\": [\"/ipfs\", \"/ipns\"]}}';
  #     ipfs config --json Pinning.RemoteServices '[\"Pinata\"]';
  #     ipfs config --json Pinning.RemoteServices.Pinata.Policies '{\"MFS\":{\"Enable\": false,\"PinName\": \"\",\"RepinInterval\": \"1m\"}}';
  #     ipfs config --json Peering.Peers '[{\"ID\": \"Qma8ddFEQWEU8ijWvdxXm3nxU7oHsRtCykAaVz8WUYhiKn\", \"Addrs\": [\"/dnsaddr/bitswap.pinata.cloud\"]}]';
  #     exec ipfs daemon --migrate=true --agent-version-suffix=docker"
  #   envVars:
  #     - key: IPFS_PATH
  #       value: /data/ipfs
  #     - key: PINATA_API_JWT
  #       sync: false
  #   disk:
  #     name: ipfs-data
  #     mountPath: /data/ipfs

  # Image Guard API
  - type: web
    name: image-guard
    runtime: image
    image:
      url: ghcr.io/0xintuition/image-guard:latest
    envVars:
      - key: API_PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: database
          property: connectionString
      - key: FLAG_HF_CLASSIFICATION
        value: true
      - key: HF_TOKEN
        sync: false
      - fromGroup: ipfs
      - fromGroup: pinata-secrets

databases:
  - name: database
    databaseName: storage
    user: testuser
    ipAllowList: []

envVarGroups:
  - name: aws-credentials
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-west-2

  - name: hasura-secrets
    envVars:
      - key: HASURA_GRAPHQL_ADMIN_SECRET
        generateValue: true
      - key: PINATA_AUTH
        sync: false

  - name: pinata-secrets
    envVars:
      - key: PINATA_API_JWT
        sync: false
      - key: PINATA_GATEWAY_TOKEN
        sync: false

  - name: rpc-mainnet
    envVars:
      - key: RPC_URL_BASE_MAINNET
        sync: false
      - key: RPC_URL_MAINNET
        sync: false
  
  - name: ipfs
    envVars:
      - key: IPFS_GATEWAY_URL
        value: https://ipfs.io
      - key: IPFS_UPLOAD_URL
        value: https://ipfs.io
