apiVersion: v1
kind: Pod
metadata:
  name: test-secrets
spec:
  serviceAccountName: secrets-access-sa
  containers:
  - name: test
    image: amazon/aws-cli
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets"
      readOnly: true
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets" 