apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api
  - consumers/decoded
  - consumers/ipfs-upload
  - consumers/raw
  - consumers/resolver-consumer
  - ipfs
  - monitoring/log-cleanup
  - monitoring/prometheus
  - rbac/secrets-store-csi-driver-rbac.yaml
  - services/graphql
  - services/safe-content-api
  - substreams-sink

commonLabels:
  app: intuition