table:
  name: redemption
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: redemptions
  custom_root_fields:
    select_by_pk: redemption
object_relationships:
  - name: receiver
    using:
      foreign_key_constraint_on: receiver_id
  - name: sender
    using:
      manual_configuration:
        column_mapping:
          sender_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: term
    using:
      foreign_key_constraint_on: term_id
  - name: vault
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: vault
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - vault_type
        - log_index
        - term_id
        - assets
        - block_number
        - curve_id
        - fees
        - shares
        - total_shares
        - id
        - receiver_id
        - sender_id
        - transaction_hash
        - created_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - vault_type
        - log_index
        - term_id
        - assets
        - block_number
        - curve_id
        - fees
        - shares
        - total_shares
        - id
        - receiver_id
        - sender_id
        - transaction_hash
        - created_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
