table:
  name: predicate_object
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: predicate_objects
  custom_root_fields: {}
object_relationships:
  - name: object
    using:
      manual_configuration:
        column_mapping:
          object_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
  - name: predicate
    using:
      manual_configuration:
        column_mapping:
          predicate_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
array_relationships:
  - name: triples
    using:
      manual_configuration:
        column_mapping:
          object_id: object_id
          predicate_id: predicate_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - object_id
        - opposer_count
        - predicate_id
        - supporter_count
        - total_market_cap
        - total_position_count
        - triple_count
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - object_id
        - opposer_count
        - predicate_id
        - supporter_count
        - total_market_cap
        - total_position_count
        - triple_count
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
