table:
  name: term_total_state_change_stats_hourly
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - difference
        - first_total_market_cap
        - last_total_market_cap
        - term_id
        - bucket
      filter: {}
      limit: 1000
    comment: ""
  - role: frontend
    permission:
      columns:
        - difference
        - first_total_market_cap
        - last_total_market_cap
        - term_id
        - bucket
      filter: {}
      limit: 1000
    comment: ""
