table:
  name: account
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: accounts
  custom_root_fields:
    select_by_pk: account
object_relationships:
  - name: atom
    using:
      manual_configuration:
        column_mapping:
          atom_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
array_relationships:
  - name: atoms
    using:
      manual_configuration:
        column_mapping:
          id: creator_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
  - name: deposits_received
    using:
      manual_configuration:
        column_mapping:
          id: receiver_id
        insertion_order: null
        remote_table:
          name: deposit
          schema: public
  - name: deposits_sent
    using:
      manual_configuration:
        column_mapping:
          id: sender_id
        insertion_order: null
        remote_table:
          name: deposit
          schema: public
  - name: fee_transfers
    using:
      manual_configuration:
        column_mapping:
          id: sender_id
        insertion_order: null
        remote_table:
          name: fee_transfer
          schema: public
  - name: positions
    using:
      manual_configuration:
        column_mapping:
          id: account_id
        insertion_order: null
        remote_table:
          name: position
          schema: public
  - name: redemptions_received
    using:
      manual_configuration:
        column_mapping:
          id: receiver_id
        insertion_order: null
        remote_table:
          name: redemption
          schema: public
  - name: redemptions_sent
    using:
      manual_configuration:
        column_mapping:
          id: sender_id
        insertion_order: null
        remote_table:
          name: redemption
          schema: public
  - name: signals
    using:
      manual_configuration:
        column_mapping:
          id: account_id
        insertion_order: null
        remote_table:
          name: signal
          schema: public
  - name: triples
    using:
      manual_configuration:
        column_mapping:
          id: creator_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
  - name: season2_iq_ledger_entries
    using:
      manual_configuration:
        column_mapping:
          id: account_id
        insertion_order: null
        remote_table:
          name: season2_iq_ledger
          schema: public
remote_relationships:
  - definition:
      to_source:
        field_mapping:
          image: original_url
        relationship_type: object
        source: cache
        table:
          name: cached_image
          schema: cached_images
    name: cached_image
select_permissions:
  - role: anonymous
    permission:
      columns:
        - atom_id
        - id
        - image
        - label
        - type
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - atom_id
        - id
        - image
        - label
        - type
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
