table:
  name: pnl_leaderboard_entry
  schema: public
select_permissions:
  - role: anonymous
    permission:
      columns: '*'
      filter: {}
      allow_aggregations: true
  - role: frontend
    permission:
      columns: '*'
      filter: {}
      allow_aggregations: true
