table:
  name: season2_epoch_price
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: season2_epoch_prices
  custom_root_fields:
    select_by_pk: season2_epoch_price
object_relationships:
  - name: season2_epoch
    using:
      manual_configuration:
        column_mapping:
          epoch: epoch
        insertion_order: null
        remote_table:
          name: season2_epoch
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - epoch
        - snapshot_count
        - average_price_usd
        - computed_at
        - updated_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - epoch
        - snapshot_count
        - average_price_usd
        - computed_at
        - updated_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
