table:
  name: signal
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: signals
  custom_root_fields:
    select_by_pk: signal
object_relationships:
  - name: account
    using:
      manual_configuration:
        column_mapping:
          account_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: deposit
    using:
      manual_configuration:
        column_mapping:
          deposit_id: id
        insertion_order: null
        remote_table:
          name: deposit
          schema: public
  - name: redemption
    using:
      manual_configuration:
        column_mapping:
          redemption_id: id
        insertion_order: null
        remote_table:
          name: redemption
          schema: public
  - name: term
    using:
      manual_configuration:
        column_mapping:
          term_id: id
        insertion_order: null
        remote_table:
          name: term
          schema: public
  - name: vault
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: vault
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - atom_id
        - term_id
        - triple_id
        - block_number
        - curve_id
        - delta
        - account_id
        - deposit_id
        - id
        - redemption_id
        - transaction_hash
        - created_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
