table:
  name: signal_stats_hourly
  schema: public
object_relationships:
  - name: term
    using:
      manual_configuration:
        column_mapping:
          term_id: id
        insertion_order: null
        remote_table:
          name: term
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - count
        - curve_id
        - term_id
        - volume
        - bucket
      filter: {}
      limit: 1000
    comment: ""
