table:
  name: event
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: events
  custom_root_fields:
    select_by_pk: event
object_relationships:
  - name: atom
    using:
      manual_configuration:
        column_mapping:
          atom_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
  - name: deposit
    using:
      manual_configuration:
        column_mapping:
          deposit_id: id
        insertion_order: null
        remote_table:
          name: deposit
          schema: public
  - name: fee_transfer
    using:
      manual_configuration:
        column_mapping:
          fee_transfer_id: id
        insertion_order: null
        remote_table:
          name: fee_transfer
          schema: public
  - name: redemption
    using:
      manual_configuration:
        column_mapping:
          redemption_id: id
        insertion_order: null
        remote_table:
          name: redemption
          schema: public
  - name: protocol_fee_accrued
    using:
      manual_configuration:
        column_mapping:
          protocol_fee_accrued_id: id
        insertion_order: null
        remote_table:
          name: protocol_fee_accrued
          schema: public
  - name: triple
    using:
      manual_configuration:
        column_mapping:
          triple_id: term_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - transaction_hash
        - atom_id
        - block_number
        - created_at
        - triple_id
        - deposit_id
        - fee_transfer_id
        - id
        - protocol_fee_accrued_id
        - redemption_id
        - type
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - transaction_hash
        - atom_id
        - block_number
        - created_at
        - triple_id
        - deposit_id
        - fee_transfer_id
        - id
        - protocol_fee_accrued_id
        - redemption_id
        - type
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
