table:
  name: fee_transfer
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: fee_transfers
  custom_root_fields:
    select_by_pk: fee_transfer
object_relationships:
  - name: receiver
    using:
      manual_configuration:
        column_mapping:
          receiver_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: sender
    using:
      manual_configuration:
        column_mapping:
          sender_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - transaction_hash
        - amount
        - block_number
        - created_at
        - id
        - receiver_id
        - sender_id
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
