table:
  name: subject_predicate
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: subject_predicates
  custom_root_fields: {}
object_relationships:
  - name: predicate
    using:
      manual_configuration:
        column_mapping:
          predicate_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
  - name: subject
    using:
      manual_configuration:
        column_mapping:
          subject_id: term_id
        insertion_order: null
        remote_table:
          name: atom
          schema: public
array_relationships:
  - name: triples
    using:
      manual_configuration:
        column_mapping:
          predicate_id: predicate_id
          subject_id: subject_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - predicate_id
        - subject_id
        - total_market_cap
        - total_position_count
        - triple_count
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
