table:
  name: atom
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: atoms
  custom_root_fields:
    select_by_pk: atom
object_relationships:
  - name: controller
    using:
      manual_configuration:
        column_mapping:
          wallet_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: creator
    using:
      manual_configuration:
        column_mapping:
          creator_id: id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: term
    using:
      manual_configuration:
        column_mapping:
          term_id: id
        insertion_order: null
        remote_table:
          name: term
          schema: public
  - name: value
    using:
      manual_configuration:
        column_mapping:
          term_id: id
        insertion_order: null
        remote_table:
          name: atom_value
          schema: public
array_relationships:
  - name: accounts
    using:
      manual_configuration:
        column_mapping:
          term_id: atom_id
        insertion_order: null
        remote_table:
          name: account
          schema: public
  - name: as_object_predicate_objects
    using:
      manual_configuration:
        column_mapping:
          term_id: object_id
        insertion_order: null
        remote_table:
          name: predicate_object
          schema: public
  - name: as_object_triples
    using:
      manual_configuration:
        column_mapping:
          term_id: object_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
  - name: as_predicate_predicate_objects
    using:
      manual_configuration:
        column_mapping:
          term_id: predicate_id
        insertion_order: null
        remote_table:
          name: predicate_object
          schema: public
  - name: as_predicate_triples
    using:
      manual_configuration:
        column_mapping:
          term_id: predicate_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
  - name: as_subject_triples
    using:
      manual_configuration:
        column_mapping:
          term_id: subject_id
        insertion_order: null
        remote_table:
          name: triple
          schema: public
  - name: positions
    using:
      manual_configuration:
        column_mapping:
          term_id: term_id
        insertion_order: null
        remote_table:
          name: position
          schema: public
  - name: signals
    using:
      manual_configuration:
        column_mapping:
          term_id: atom_id
        insertion_order: null
        remote_table:
          name: signal
          schema: public
remote_relationships:
  - definition:
      to_source:
        field_mapping:
          image: original_url
        relationship_type: object
        source: cache
        table:
          name: cached_image
          schema: cached_images
    name: cached_image
select_permissions:
  - role: anonymous
    permission:
      columns:
        - resolving_status
        - type
        - log_index
        - term_id
        - value_id
        - block_number
        - creator_id
        - data
        - emoji
        - image
        - label
        - raw_data
        - transaction_hash
        - wallet_id
        - created_at
        - updated_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
