table:
  name: vault
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: vaults
  custom_root_fields:
    select_by_pk: vault
object_relationships:
  - name: term
    using:
      foreign_key_constraint_on: term_id
array_relationships:
  - name: deposits
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: deposit
          schema: public
  - name: positions
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: position
          schema: public
  - name: redemptions
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: redemption
          schema: public
  - name: share_price_change_stats_daily
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: share_price_change_stats_daily
          schema: public
  - name: share_price_change_stats_hourly
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: share_price_change_stats_hourly
          schema: public
  - name: share_price_change_stats_monthly
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: share_price_change_stats_monthly
          schema: public
  - name: share_price_change_stats_weekly
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: share_price_change_stats_weekly
          schema: public
  - name: share_price_changes
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: share_price_change
          schema: public
  - name: signals
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: signal
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - block_number
        - log_index
        - term_id
        - position_count
        - current_share_price
        - curve_id
        - market_cap
        - total_assets
        - total_shares
        - transaction_hash
        - created_at
        - updated_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - block_number
        - log_index
        - term_id
        - position_count
        - current_share_price
        - curve_id
        - market_cap
        - total_assets
        - total_shares
        - transaction_hash
        - created_at
        - updated_at
      filter: {}
      limit: 250
      allow_aggregations: true
    comment: ""
