table:
  name: share_price_change
  schema: public
configuration:
  column_config: {}
  custom_column_names: {}
  custom_name: share_price_changes
  custom_root_fields:
    select_by_pk: share_price_change
object_relationships:
  - name: term
    using:
      manual_configuration:
        column_mapping:
          term_id: id
        insertion_order: null
        remote_table:
          name: term
          schema: public
  - name: vault
    using:
      manual_configuration:
        column_mapping:
          curve_id: curve_id
          term_id: term_id
        insertion_order: null
        remote_table:
          name: vault
          schema: public
select_permissions:
  - role: anonymous
    permission:
      columns:
        - vault_type
        - block_timestamp
        - id
        - log_index
        - term_id
        - block_number
        - curve_id
        - share_price
        - total_assets
        - total_shares
        - transaction_hash
        - updated_at
      filter: {}
      limit: 100
      allow_aggregations: true
    comment: ""
  - role: frontend
    permission:
      columns:
        - vault_type
        - block_timestamp
        - id
        - log_index
        - term_id
        - block_number
        - curve_id
        - share_price
        - total_assets
        - total_shares
        - transaction_hash
        - updated_at
      filter: {}
      limit: 100
      allow_aggregations: true
    comment: ""
