apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: envio-indexer
  name: envio-indexer
spec:
  ports:
    - name: envio-indexer
      port: 3000
      targetPort: 3000
  selector:
    app: envio-indexer