apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-db
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: timescale-db
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
            - name: timescale-db-data
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: prod-base-mainnet-v-1-5-vector-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-base-mainnet-v-1-5-vector-aws-secrets"
  volumeClaimTemplates:
    - metadata:
        name: timescale-db-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: gp3
        resources:
          requests:
            storage: 30Gi
