apiVersion: apps/v1
kind: Deployment
metadata:
  name: resolver-consumer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: resolver-consumer
          image: ghcr.io/0xintuition/consumer:2.0.20
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
            - mountPath: /var/log/app
              name: resolver-logs
          envFrom:
            - secretRef:
                name: prod-base-sepolia-v2-resolver-consumer-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-base-sepolia-v2-prod-base-sepolia-v2-resolver-consumer-secrets"
        - name: resolver-logs
          persistentVolumeClaim:
            claimName: prod-base-sepolia-v2-resolver-logs