apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['api:3000'] 
          - targets: ['decoded-consumer:3002']
      - job_name: 'decoded-consumer'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: decoded-consumer

    rule_files:
      - 'alert.rules'
      - 'recording.rules'
