apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-rolebinding.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
commonLabels:
  component: prometheus 