apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migrations
spec:
  template:
    metadata:
      labels:
        app: hasura-migrations
    spec:
      containers:
        - name: hasura-migrations
          image: ghcr.io/0xintuition/hasura-migrations:latest
          imagePullPolicy: Always
          env:
            - name: HASURA_GRAPHQL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: HASURA_GRAPHQL_ENDPOINT
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: HASURA_GRAPHQL_ADMIN_SECRET
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-secrets
  backoffLimit: 20
