apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: decoded-consumer
  name: decoded-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decoded-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: decoded-consumer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - ./consumer
            - --mode
            - decoded
          envFrom:
            - secretRef:
                name: decoded-aws-secrets
          image: ghcr.io/0xintuition/consumer:latest
          imagePullPolicy: Always
          name: decoded-consumer
          ports:
            - containerPort: 3002
              protocol: TCP
          volumeMounts:
            - name: decoded-logs
              mountPath: /logs
              readOnly: false
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: decoded-logs
          persistentVolumeClaim:
            claimName: decoded-logs
