apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-engine
  labels:
    io.kompose.service: base-sepolia-graphql-engine
spec:
  selector:
    matchLabels:
      io.kompose.service: base-sepolia-graphql-engine
  template:
    metadata:
      labels:
        io.kompose.service: base-sepolia-graphql-engine
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: graphql-engine
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: dev-sepolia-hasura-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dev-base-sepolia-dev-sepolia-hasura-aws-secrets"