apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secret-provider.yaml

namePrefix: base-sepolia-


patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: graphql-engine
- path: migrations-patch.yaml
  target:
    kind: Deployment
    name: hasura-migrations

labels:
- includeSelectors: true
  pairs:
    network: base-sepolia
