apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-proxy
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: rpc-proxy
          image: ghcr.io/0xintuition/rpc-proxy:1.0.51
          imagePullPolicy: Always 
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-rpc-proxy-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-prod-rpc-proxy-aws-secrets"