apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: substreams-sink
  name: substreams-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: substreams-sink
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: substreams-sink
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - $(SUBSTREAMS_ENDPOINT)
            - $(SUBSTREAMS_PACKAGE)
            - $(SUBSTREAMS_MODULE)
            - "$(SUBSTREAMS_START_BLOCK):"
          name: substreams-sink
          volumeMounts:
            - mountPath: /var/lib/data
              name: substreams-data
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: substreams-data
          persistentVolumeClaim:
            claimName: substreams-data
