apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: substreams-sink
  name: substreams-sink
spec:
  ports:
    - name: substreams-sink
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: substreams-sink
