apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prod-base-sepolia-consumer-api-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "new-be-secrets-prod-base-sepolia-v2"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "CONSUMER_API_PORT"
            objectAlias: "CONSUMER_API_PORT"
          - path: "RESOLVER_QUEUE_URL"
            objectAlias: "RESOLVER_QUEUE_URL"
  secretObjects:
    - secretName: "prod-base-sepolia-consumer-api-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "CONSUMER_API_PORT"
          key: "CONSUMER_API_PORT"
        - objectName: "RESOLVER_QUEUE_URL"
          key: "RESOLVER_QUEUE_URL"
        
