apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ipfs-upload
  - secret-provider.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ipfs-upload-consumer

commonLabels:
  network: linea-sepolia
