apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-linea-sepolia-ipfs-upload-logs
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi