# TODO: Remove the `RPC_URL_BASE_MAINNET` when migrated to a version above 1.0.27
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: decoded-consumer-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod-base-sepolia-v-1-5-vector"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "CONSUMER_METRICS_API_PORT"
            objectAlias: "CONSUMER_METRICS_API_PORT"
          - path: "CONSUMER_TYPE"
            objectAlias: "CONSUMER_TYPE"
          - path: "BACKEND_SCHEMA"
            objectAlias: "BACKEND_SCHEMA"
  secretObjects:
    - secretName: "decoded-consumer-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "CONSUMER_METRICS_API_PORT"
          key: "CONSUMER_METRICS_API_PORT"
        - objectName: "CONSUMER_TYPE"
          key: "CONSUMER_TYPE"
        - objectName: "BACKEND_SCHEMA"
          key: "BACKEND_SCHEMA"
