global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']
      - targets: ['decoded_consumer:3001']

rule_files:
  - 'alert.rules'
  - 'recording.rules'