apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replicator
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'https://github.com/0xintuition/intuition-rs.git'
    targetRevision: francois/add-iac
    path: devops/argocd/manifests/main-ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
