apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vector-db
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'https://github.com/0xintuition/intuition-rs.git'
    targetRevision: luis/eng-6546-vector-db-support
    path: devops/aws-rolling-releases/vector_db/
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: vector-db
          patch: |-
            - op: replace
              path: /spec/template/spec/serviceAccountName
              value: prod-eks-secrets-access-sa
            - op: replace
              path: /spec/template/spec/volumes/1/csi/volumeAttributes/secretProviderClass
              value: prod-sepolia-vector-db-aws-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
