apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-service-reader
subjects:
- kind: ServiceAccount
  name: prod-eks-secrets-access-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus-service-reader
  apiGroup: rbac.authorization.k8s.io 