apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: raw-consumer
  name: raw-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: raw-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: raw-consumer
    spec:
      containers:
        - args:
            - ./consumer
            - --mode
            - raw
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: CONSUMER_TYPE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CONSUMER_TYPE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_URL
            - name: DECODED_LOGS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DECODED_LOGS_QUEUE_URL
            - name: INDEXING_SOURCE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INDEXING_SOURCE
            - name: LOCALSTACK_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LOCALSTACK_URL
            - name: RAW_CONSUMER_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RAW_CONSUMER_QUEUE_URL
            - name: RPC_URL_BASE_MAINNET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RPC_URL_BASE_MAINNET
            - name: RPC_URL_MAINNET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RPC_URL_MAINNET
            - name: RUST_LOG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RUST_LOG
          image: ghcr.io/0xintuition/consumer:latest
          imagePullPolicy: Always
          name: raw-consumer
          ports:
            - containerPort: 8003
              protocol: TCP
          volumeMounts:
            - mountPath: /var/log/app
              name: raw-logs
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      restartPolicy: Always
      volumes:
        - name: raw-logs
          persistentVolumeClaim:
            claimName: raw-logs
