apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-provider.yaml
  - indexer-migrations.yaml

namePrefix: "prod-base-mainnet-v2-"

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: graphql-engine

  - path: migrations-patch.yaml
    target:
      kind: Job
      name: hasura-migrations

commonLabels:
  network: base-mainnet
  io.kompose.service: prod-base-mainnet-v2-graphql-engine

