apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: histoflux
  name: histoflux
spec:
  type: ClusterIP 
  ports:
    - name: "3009"
      port: 3009
      targetPort: 3009
  selector:
    io.kompose.service: histoflux