apiVersion: v1
kind: Pod
metadata:
  name: cert-debug
  namespace: cert-manager
spec:
  serviceAccountName: cert-manager
  containers:
  - name: awscli
    image: amazonlinux:2
    command: ["sleep", "3600"]
  restartPolicy: Never