apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-postgres
  template:
    metadata:
      labels:
        app: test-postgres
    spec:
      containers:
      - name: test-postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "intuition"
        - name: POSTGRES_PASSWORD
          value: "w5YcryExSYc5Nm1"
        - name: POSTGRES_DB
          value: "storage"
        - name: POSTGRES_HOST
          value: "new-be-storage.cfoc8w15ytnt.us-west-2.rds.amazonaws.com"
        - name: POSTGRES_PORT
          value: "5435"
        - name: POSTGRES_SSLMODE
          value: "require"
        command: ["sh", "-c", "while true; do sleep 30; done;"]
