apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/resolver
  - secret-provider.yaml
  - pvc.yaml

namePrefix: "prod-linea-mainnet-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: resolver-consumer

commonLabels:
  network: linea-mainnet