apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: envio-indexer
  name: envio-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envio-indexer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: envio-indexer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: envio-indexer
          volumeMounts:
            - mountPath: /var/lib/data
              name: envio-indexer-data
      restartPolicy: Always
      volumes:
        - name: envio-indexer-data
          persistentVolumeClaim:
            claimName: envio-indexer-data
