apiVersion: batch/v1
kind: Job
metadata:
  name: hasura-migrations
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      initContainers:
        - name: wait
          image: busybox
          command: ['sh', '-c', 'sleep 5']
      containers:
        - name: hasura-migrations
          image: ghcr.io/0xintuition/hasura-migrations:latest
          envFrom:
            - secretRef:
                name: hasura-aws-secrets
      restartPolicy: Never
