apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: nginx.prod.base-sepolia.intuition.sh
spec:
  type: LoadBalancer
  ingressClassName: nginx
  tls:
  - hosts:
      - nginx.prod.base-sepolia.intuition.sh
    secretName: nginx-prod-base-sepolia-cert
  rules:
    - host: nginx.prod.base-sepolia.intuition.sh
      http:
        paths:
          - path: /v1/graphql
            pathType: Prefix
            backend:
              service:
                name: prod-base-sepolia-v-1-5-vector-graphql-engine
                port:
                  number: 8080
