apiVersion: v1
kind: ConfigMap
metadata:
  name: ipfs-scripts
data:
  entrypoint.sh: |
    #!/bin/sh
    set -e
    
    echo "Starting IPFS daemon..."
    
    # Wait for secret to be available (max 30 seconds)
    for i in $(seq 1 30); do
      if [ -f /mnt/secrets/PINATA_API_JWT ]; then
        break
      fi
      echo "Waiting for secret file..."
      sleep 1
    done
    
    # Read the secret from mounted volume
    PINATA_API_JWT=$(cat /mnt/secrets/PINATA_API_JWT)
    export PINATA_API_JWT
    
    # Initialize IPFS if not already initialized
    if [ ! -f /data/ipfs/config ]; then
      ipfs init
    fi
    
    # Configure IPFS before starting daemon
    ipfs config Addresses.API /ip4/0.0.0.0/tcp/5001
    ipfs config Addresses.Gateway /ip4/0.0.0.0/tcp/8080
    ipfs config --json Gateway.PublicGateways '{"localhost": {"UseSubdomains": false,"Paths": ["/ipfs", "/ipns"]},"ipfs": {"UseSubdomains": false,"Paths": ["/ipfs", "/ipns"]}}'
    
    # Start the daemon in the foreground
    exec ipfs daemon --migrate 