apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage-class.yaml
  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - service-account.yaml
  - secret-provider.yaml

commonLabels:
  component: ipfs 