apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "new-be-secrets"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "PINATA_API_JWT"
            objectAlias: "PINATA_API_JWT"
  secretObjects:
    - secretName: "aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "PINATA_API_JWT"
          key: "PINATA_API_JWT"
