apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: consumer-api
          image: ghcr.io/0xintuition/consumer-api:2.0.1
          imagePullPolicy: Always 
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: dev-base-mainnet-consumer-api-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dev-base-mainnet-dev-base-mainnet-consumer-api-aws-secrets"