apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: resolver-logs
  name: resolver-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
