apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoded-consumer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: decoded-consumer
          image: ghcr.io/0xintuition/consumer:2.0.26
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "3"
              memory: "2Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: dev-decoded-consumer-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dev-base-mainnet-dev-decoded-consumer-secrets"