apiVersion: apps/v1
kind: Deployment
metadata:
  name: histocrawler
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: histocrawler
          args:
            - --network
            - base-mainnet
            - --output
            - postgres
          image: ghcr.io/0xintuition/histocrawler:2.0.3
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-histocrawler-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-base-mainnet-prod-histocrawler-aws-secrets"