apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: histoflux-aws-secrets
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "new-be-secrets-prod-linea-mainnet-v2"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "ENVIRONMENT_NAME"
            objectAlias: "ENVIRONMENT_NAME"
          - path: "INDEXER_SCHEMA"
            objectAlias: "INDEXER_SCHEMA"
            
  secretObjects:
    - secretName: "histoflux-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
          key: "ENVIRONMENT_NAME"
        - objectName: "INDEXER_SCHEMA"
          key: "INDEXER_SCHEMA"
