[package]
name = "substreams-sink-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
async-stream = "0.3"
futures03 = { version = "0.3.31", package = "futures", features = ["compat"] }
reqwest = "0.12.8"
tokio.workspace = true
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-retry = "0.3"
tonic = { version = "0.12", features = ["gzip", "tls-roots"] }
prost = "0.13"
prost-types = "0.13"
thiserror = "1"
chrono = "0.4.38"
serde.workspace = true
macon = "1.2.0"
hex.workspace = true
serde_json.workspace = true
aws-config = { version = "1.0.1", features = ["behavior-version-latest"] }
aws-sdk-sqs = { version = "1.3.0" }
aws-smithy-runtime-api = "1.7.0"
dotenvy = "0.15.7"
