apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: aws-secrets
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
  parameters:
    objects: |
      - objectName: "new-be-secrets"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: DATABASE_URL
            objectAlias: DATABASE_URL
