apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-db-vectorizer
spec:
  selector:
    matchLabels:
      io.kompose.service: timescale-db-vectorizer

  template:
    metadata:
      labels:
        io.kompose.service: timescale-db-vectorizer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: timescale-db-vectorizer
          image: timescale/pgai-vectorizer-worker:v0.10.5
          imagePullPolicy: Always 
          ports:
          - containerPort: 5435
            protocol: TCP
          