apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-provider.yaml

namePrefix: "prod-base-mainnet-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: envio-indexer

commonLabels:
  network: base-mainnet