apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    region: us-west-2 
    objects: |
      - objectName: "new-be-secrets"
        objectType: "secretsmanager"



 