apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-provider.yaml

namePrefix: "dev-base-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: substreams-sink

commonLabels:
  network: base-sepolia