apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-engine
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: graphql-engine
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "6Gi"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-base-mainnet-v2-hasura-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-base-mainnet-v2-prod-base-mainnet-v2-hasura-aws-secrets"
