apiVersion: apps/v1
kind: Deployment
metadata:
  name: decoded-consumer
spec:
  selector:
    matchLabels:
      app: decoded-consumer
  template:
    metadata:
      labels:
        app: decoded-consumer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
      - name: decoded-consumer
        image: ghcr.io/0xintuition/consumer:latest
        args: ["./consumer", "--mode", "decoded"]
        ports:
        - containerPort: 3002
        env:
        - name: AWS_REGION
          value: "us-west-2"
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: "regional"
        - name: AWS_ROLE_ARN
          value: "arn:aws:iam::064662847354:role/aws-secrets"
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets"
          readOnly: true
        - name: decoded-logs
          mountPath: "/var/log/app"
        - name: aws-iam-token
          mountPath: "/var/run/secrets/eks.amazonaws.com/serviceaccount"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets"
      - name: decoded-logs
        persistentVolumeClaim:
          claimName: decoded-logs
      - name: aws-iam-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 86400
    
    