apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- pvc.yaml
- service.yaml
- service-account.yaml

labels:
- includeSelectors: true
  pairs:
    component: decoded-consumer
