apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- storage-class.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- service-account.yaml

labels:
- includeSelectors: true
  pairs:
    component: decoded-consumer
