apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: decoded-logs
  name: decoded-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
