apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consumer-raw
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: francois/add-iac
            env: dev-base-sepolia
            namespace: dev-base-sepolia-v2-0-0
  template:
    metadata:
      name: '{{ cluster }}-namespacedapps-{{namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: ssh://git@github.com/0xintuition/intuition-rs.git
        path: 'devops/aws/consumers/overlays/{{env}}/raw'
        targetRevision: '{{ revision }}'
        kustomize: {}
      destination:
        server: '{{ server }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
