apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consumer-decoded
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: francois/add-iac
            env: dev-base-sepolia
            namespace: dev-base-sepolia-v2-0-0
  template:
    metadata:
      name: '{{ cluster }}-namespacedapps-{{namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xintuition/intuition-rs.git
        path: 'devops/aws/consumers/overlays/{{env}}/decoded'
        targetRevision: '{{ revision }}'
        kustomize:
          patches:
            - target:
                kind: Queue
                name: resolver-queue
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: '{{namespace}}-resolver'
                - op: replace
                  path: /spec/forProvider/name
                  value: '{{cluster}}-{{namespace}}-resolver'
            - target:
                kind: Deployment
                name: decoded-consumer
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{cluster}}-{{namespace}}-secrets-access-sa'
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: RESOLVER_QUEUE_URL
                    value: 'https://arn:aws:sqs:us-west-2:064662847354:{{cluster}}-{{namespace}}-resolver'
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: DECODED_LOGS_QUEUE_URL
                    value: 'https://arn:aws:sqs:us-west-2:064662847354:{{cluster}}-{{namespace}}-decoded-logs.fifo'

      destination:
        server: '{{ server }}'
        namespace: '{{ namespace }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
