apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: consumer-resolver
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: francois/add-iac
            env: dev-base-sepolia
            namespace: dev-base-sepolia-v2-0-0
  template:
    metadata:
      name: '{{.cluster}}-consumer-resolver-{{.namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xintuition/intuition-rs.git
        path: 'devops/aws/consumers/overlays/{{.env}}/resolver'
        targetRevision: '{{.revision}}'
        kustomize:
          patches:
            - target:
                kind: Queue
                name: ipfs-upload
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: '{{.namespace}}-ipfs-upload'
                - op: replace
                  path: /spec/forProvider/name
                  value: '{{.cluster}}-{{.namespace}}-ipfs-upload'
            - target:
                kind: Deployment
                name: resolver-consumer
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{.cluster}}-{{.namespace}}-secrets-access-sa'
                - op: add
                  path: /spec/template/spec/containers/0/envFrom/-
                  value:
                    secretRef:
                      name: 'main-db-creds'
                    prefix: "MAINDB_"
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: DATABASE_URL
                    value: 'postgres://$(MAINDB_username):$(MAINDB_password)@$(MAINDB_endpoint)/{{.namespace | replace "-" "_"}}?sslmode=require'
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: RESOLVER_QUEUE_URL
                    value: 'https://sqs.us-west-2.amazonaws.com/064662847354/{{.cluster}}-{{.namespace}}-resolver'
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: IPFS_UPLOAD_QUEUE_URL
                    value: 'https://sqs.us-west-2.amazonaws.com/064662847354/{{.cluster}}-{{.namespace}}-ipfs-upload'

      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
