apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: histoflux
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: base-sepolia
            env: prod-base-sepolia-v-1-5
            namespace: prod-base-sepolia-v-1-5
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: base-sepolia
            env: prod-base-sepolia-v-1-0
            namespace: prod-base-sepolia-v-1-0
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: base-mainnet
            env: prod-base-mainnet-v-1-0
            namespace: prod-base-mainnet-v-1-0
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: linea-mainnet
            env: prod-linea-mainnet-v-1-0
            namespace: prod-linea-mainnet-v-1-0
  template:
    metadata:
      name: '{{.cluster}}-histoflux-{{.namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xintuition/intuition-rs.git
        path: 'devops/aws-rolling-releases/histoflux/overlays/{{.env}}'
        targetRevision: '{{.revision}}'
        kustomize:
          patches:
            - target:
                kind: Queue
                name: raw-logs-queue
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: '{{.namespace}}-raw-logs'
                - op: replace
                  path: /spec/forProvider/name
                  value: '{{.cluster}}-{{.namespace}}-raw-logs.fifo'
            - target:
                kind: Deployment
                name: histoflux
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{.cluster}}-{{.namespace}}-secrets-access-sa'
                - op: add
                  path: /spec/template/spec/containers/0/envFrom/-
                  value:
                    secretRef:
                      name: 'main-db-creds'
                    prefix: "MAINDB_"
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: INDEXER_DATABASE_URL
                    value: 'postgres://$(MAINDB_username):$(MAINDB_password)@$(MAINDB_endpoint)/histoflux?sslmode=require'
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: RAW_CONSUMER_QUEUE_URL
                    value: 'https://sqs.us-west-2.amazonaws.com/064662847354/{{.cluster}}-{{.namespace}}-raw-logs.fifo'
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
