apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: histocrawler
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: base-sepolia
            env: base-sepolia
            namespace: prod-base-sepolia-v-1-5
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: prod-base-sepolia-deployment
            chain: base-sepolia
            env: base-sepolia-v1
            namespace: prod-base-sepolia-v-1-0

  template:
    metadata:
      name: '{{.cluster}}-histocrawler-{{.namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: https://github.com/0xintuition/intuition-rs.git
        path: 'devops/aws-rolling-releases/histocrawler/overlays/{{.env}}'
        targetRevision: '{{.revision}}'
        kustomize:
          patches:
            - target:
                kind: Deployment
                name: histocrawler
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{.cluster}}-{{.namespace}}-secrets-access-sa'
                - op: add
                  path: /spec/template/spec/containers/0/envFrom/-
                  value:
                    secretRef:
                      name: 'main-db-creds'
                    prefix: "MAINDB_"
                - op: add
                  path: /spec/template/spec/containers/0/env/-
                  value:
                    name: HISTOCRAWLER_DATABASE_URL
                    value: 'postgres://$(MAINDB_username):$(MAINDB_password)@$(MAINDB_endpoint)/histoflux?sslmode=require'
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
