apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timescale-db
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: next
            env: prod-linea-mainnet-v-1-0
            namespace: prod-linea-mainnet-v-1-0

  template:
    metadata:
      name: '{{.cluster}}-timescale-db-{{.namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/0xintuition/intuition-rs.git'
        targetRevision: '{{.revision}}'
        path: 'devops/aws-rolling-releases/timescale_db/overlays/{{.env}}'
        kustomize:
          namePrefix: '{{.namespace}}-'
          patches:
            - target:
                kind: SecretProviderClass
                name: 'timescaledb-aws-secrets'
              patch: |-
                - op: replace
                  path: /spec/secretObjects/0/secretName
                  value: '{{.namespace}}-timescaledb-aws-secrets'
            - target:
                kind: StatefulSet
                name: timescale-db
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{.cluster}}-secrets-access-sa'
                - op: replace
                  path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
                  value: '{{.namespace}}-timescaledb-aws-secrets'
                - op: replace
                  path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
                  value: '{{.namespace}}-timescaledb-aws-secrets'
                - op: replace
                  path: /spec/template/spec/containers/0/resources/requests/cpu
                  value: "1"
                - op: replace
                  path: /spec/template/spec/containers/0/resources/limits/cpu
                  value: "1"
            - target:
                kind: Job
                name: timescale-db-pgai
              patch: |-
                - op: replace
                  path: /spec/template/spec/serviceAccountName
                  value: '{{.cluster}}-secrets-access-sa'
                - op: replace
                  path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
                  value: '{{.namespace}}-timescaledb-aws-secrets'
                - op: replace
                  path: /spec/template/spec/containers/0/envFrom/0/secretRef/name
                  value: '{{.namespace}}-timescaledb-aws-secrets'
      destination:
        server: '{{.server}}'
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
