apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-data-new
  labels:
    component: ipfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2-resizable