apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
allowVolumeExpansion: true # This is the key setting
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer