apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: histocrawler-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "new-be-secrets-prod-base-mainnet"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "RPC_URL"
            objectAlias: "RPC_URL"
          - path: "START_BLOCK"
            objectAlias: "START_BLOCK"
          - path: "INTUITION_CONTRACT_ADDRESS"
            objectAlias: "INTUITION_CONTRACT_ADDRESS"
          - path: "HISTOCRAWLER_DATABASE_URL"
            objectAlias: "HISTOCRAWLER_DATABASE_URL"
          - path: "INDEXER_SCHEMA"
            objectAlias: "INDEXER_SCHEMA"

  secretObjects:
    - secretName: "histocrawler-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "RPC_URL"
          key: "RPC_URL"
        - objectName: "START_BLOCK"
          key: "START_BLOCK"
        - objectName: "INTUITION_CONTRACT_ADDRESS"
          key: "INTUITION_CONTRACT_ADDRESS"
        - objectName: "HISTOCRAWLER_DATABASE_URL"
          key: "HISTOCRAWLER_DATABASE_URL"
        - objectName: "INDEXER_SCHEMA"
          key: "INDEXER_SCHEMA"
