apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-store-csi-driver-cluster-role
rules:
  - apiGroups: ["secrets-store.csi.x-k8s.io"]
    resources: ["secretproviderclasspodstatuses", "secretproviderclasses"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "secrets", "events"]  # Added events resource
    verbs: ["list", "get", "watch", "create"]  # Added create verb
  - apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["list", "get", "watch"]
