apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prod-mainnet-ipfs-upload-consumer-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "new-be-secrets-prod-base-mainnet"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "CONSUMER_TYPE"
            objectAlias: "CONSUMER_TYPE"
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "IMAGE_GUARD_URL"
            objectAlias: "IMAGE_GUARD_URL"
          - path: "IPFS_GATEWAY_URL"
            objectAlias: "IPFS_GATEWAY_URL"
          - path: "IPFS_UPLOAD_URL"
            objectAlias: "IPFS_UPLOAD_URL"
          - path: "IPFS_UPLOAD_QUEUE_URL"
            objectAlias: "IPFS_UPLOAD_QUEUE_URL"
          - path: "PINATA_API_JWT"
            objectAlias: "PINATA_API_JWT"
          - path: "PINATA_GATEWAY_TOKEN"
            objectAlias: "PINATA_GATEWAY_TOKEN"
          - path: "BACKEND_SCHEMA"
            objectAlias: "BACKEND_SCHEMA"
  secretObjects:
    - secretName: "prod-mainnet-ipfs-upload-consumer-secrets"  
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "CONSUMER_TYPE"
          key: "CONSUMER_TYPE"
        - objectName: "DATABASE_URL"
          key: "DATABASE_URL"
        - objectName: "IMAGE_GUARD_URL"
          key: "IMAGE_GUARD_URL"
        - objectName: "IPFS_GATEWAY_URL"
          key: "IPFS_GATEWAY_URL"
        - objectName: "IPFS_UPLOAD_URL"
          key: "IPFS_UPLOAD_URL"
        - objectName: "IPFS_UPLOAD_QUEUE_URL"
          key: "IPFS_UPLOAD_QUEUE_URL"
        - objectName: "PINATA_API_JWT"
          key: "PINATA_API_JWT"
        - objectName: "PINATA_GATEWAY_TOKEN"
          key: "PINATA_GATEWAY_TOKEN"
        - objectName: "BACKEND_SCHEMA"
          key: "BACKEND_SCHEMA"