apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: substreams-sink
  name: substreams-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: substreams-sink
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: substreams-sink
    spec:
      containers:
        - args:
            - $(SUBSTREAMS_ENDPOINT)
            - $(SUBSTREAMS_PACKAGE)
            - $(SUBSTREAMS_MODULE)
            - "$(SUBSTREAMS_START_BLOCK):"
            - --local
            - "true"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_URL
            - name: LOCALSTACK_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LOCALSTACK_URL
            - name: RAW_CONSUMER_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RAW_CONSUMER_QUEUE_URL
            - name: SUBSTREAMS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUBSTREAMS_API_TOKEN
            - name: SUBSTREAMS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUBSTREAMS_ENDPOINT
            - name: SUBSTREAMS_MODULE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUBSTREAMS_MODULE
            - name: SUBSTREAMS_PACKAGE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUBSTREAMS_PACKAGE
            - name: SUBSTREAMS_START_BLOCK
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: SUBSTREAMS_START_BLOCK
          image: ghcr.io/0xintuition/substreams-sink:latest
          imagePullPolicy: IfNotPresent
          name: substreams-sink
          volumeMounts:
            - mountPath: /var/lib/data
              name: substreams-data
      restartPolicy: Always
      volumes:
        - name: substreams-data
          persistentVolumeClaim:
            claimName: substreams-data
