apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-upload-consumer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: ipfs-upload-consumer
          image: ghcr.io/0xintuition/consumer:2.0.20
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
            - name: ipfs-upload-logs
              mountPath: /logs
              readOnly: false
          envFrom:
            - secretRef:
                name: prod-linea-mainnet-ipfs-upload-consumer-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-linea-mainnet-prod-linea-mainnet-ipfs-upload-consumer-secrets"