apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-provider.yaml
  - indexer-migrations.yaml

namePrefix: "dev-base-sepolia-"

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: graphql-engine

  - path: migrations-patch.yaml
    target:
      kind: Job
      name: hasura-migrations


  - path: indexer-migrations-patch.yaml
    target:
      kind: Job
      name: indexer-and-cache-migration

commonLabels:
  network: base-sepolia
  io.kompose.service: dev-base-sepolia-graphql-engine

