services:
  redis-db:
    extends:
      file: ./services/redis.yml
      service: redis-db

  db-init:
    extends:
      file: ./services/db.yml
      service: db-init

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    extends:
      file: ./services/db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis-db
    extends:
      file: ./services/backend.yml
      service: backend
    links:
      - db:database
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'

  sc-verifier:
    extends:
      file: ./services/smart-contract-verifier.yml
      service: smart-contract-verifier
    ports:
      - 8082:8050


  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/frontend.yml
      service: frontend


  proxy:
    depends_on:
      - backend
      - frontend
    extends:
      file: ./services/nginx.yml
      service: proxy

volumes:
  blockscout-db-data:
  logs:
  dets:
  redis-data:
