apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-db
spec:
  serviceName: vector-db
  selector:
    matchLabels:
      io.kompose.service: vector-db
  template:
    metadata:
      labels:
        io.kompose.service: vector-db
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: vector-db
          image: timescale/timescaledb-ha:pg17.4-ts2.19.2
          imagePullPolicy: Always 
          resources:
            requests:
              cpu: "3"
            limits:
              cpu: "3"
          ports:
          - containerPort: 5432
            protocol: TCP
          env:
          - name: POSTGRES_SHARED_PRELOAD_LIBRARIES
            value: "ai"
          volumeMounts:
          - name: vector-db-data
            mountPath: /var/lib/postgresql/data
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
          envFrom:
            - secretRef:
                name: prod-base-sepolia-v-1-5-vector-aws-secrets
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "prod-base-sepolia-v-1-5-vector-aws-secrets"
  volumeClaimTemplates:
  - metadata:
      name: vector-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      
      
