apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml
  - pvc.yaml
  - storageclass.yaml
  - secret-provider.yaml
  - pgai-patch.yaml

patches:
  - path: pgai-patch.yaml
    target:
      kind: Job
      name: pgai

commonLabels:
  component: vector-db 