apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vector-db-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gp3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp3 