apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hasura-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod-base-sepolia-v-1-5-vector"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "OPENAI_API_KEY"
            objectAlias: "OPENAI_API_KEY"
          - path: "POSTGRES_USER"
            objectAlias: "POSTGRES_USER"
          - path: "POSTGRES_PASSWORD"
            objectAlias: "POSTGRES_PASSWORD"
          - path: "POSTGRES_DB"
            objectAlias: "POSTGRES_DB"
          - path: "PGPORT"
            objectAlias: "PGPORT"

  secretObjects:
    - secretName: "prod-sepolia-hasura-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "OPENAI_API_KEY"
          key: "OPENAI_API_KEY"
        - objectName: "POSTGRES_USER"
          key: "POSTGRES_USER"
        - objectName: "POSTGRES_PASSWORD"
          key: "POSTGRES_PASSWORD"
        - objectName: "POSTGRES_DB"
          key: "POSTGRES_DB"
        - objectName: "PGPORT"
          key: "PGPORT"
