# Run the RAW SQS consumer connected to the test queue in test mode
[tasks.raw-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "raw",
    "--local"
]

# Run the DECODED SQS consumer connected to the test queue in test mode
[tasks.decoded-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "decoded",
    "--local"
]

# Run the RESOLVER SQS consumer connected to the test queue in test mode
[tasks.resolver-consumer-local]
env = { "RUST_LOG" = "info" }
command = "cargo"
args = [
    "run",
    "--bin",
    "consumer",
    "--",
    "--mode",
    "resolver",
    "--local"
]

# Remove docker volumes
[tasks.remove-docker-volumes]
command = "docker"
args = ["compose", "down", "-v"]

# Start the docker compose stack
[tasks.start-docker]
command = "docker"
args = ["compose", "up", "-d", "--force-recreate"]

# Build the docker image for the hasura migrations
[tasks.build-image-hasura-migrations]
command = "docker"
args = ["build", "-t", "hasura-migrations:latest", "-f", "hasura/Dockerfile", "."]

# Migrate the database
[tasks.migrate-database]
command = "hasura"
args = ["deploy", "--project", "hasura"]

# This task remove the docker volumes, start the docker compose stack, and migrate the database
[tasks.start-docker-and-migrate]
dependencies = ["remove-docker-volumes", "build-cli", "build-image-substreams-sink", "build-consumer", "build-image-guard", "build-image-hasura-migrations", "start-docker"]


# This task remove the docker volumes, start the docker compose stack
[tasks.restart]
dependencies = ["remove-docker-volumes", "start-docker"]

# Simply format and lint checking with `cargo clippy` for all targets
# in the workspace, promoting `warnings` to `errors`
[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--workspace", "--", "-Dwarnings"]