[tasks.build-consumer]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/consumer:latest", "-f", "consumer/Dockerfile", "."]

[tasks.build-image-guard]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/image-guard:latest", "-f", "image-guard/Dockerfile", "."]

[tasks.build-image-hasura-migrations]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/hasura-migrations:latest", "-f", "hasura/Dockerfile", "."]

[tasks.build-cli]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/cli:latest", "-f", "cli/Dockerfile", "."]

[tasks.build-indexer-and-cache-migrations]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/indexer-and-cache-migrations:latest", "-f", "indexer-and-cache-migrations/Dockerfile", "."]

[tasks.build-histoflux]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/histoflux:latest", "-f", "histoflux/Dockerfile", "."]

[tasks.build-rpc-proxy]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/rpc-proxy:latest", "-f", "rpc-proxy/Dockerfile", "."]

[tasks.build-histocrawler]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/histocrawler:latest", "-f", "histocrawler/Dockerfile", "."]

[tasks.build-local-migrations]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/local-migrations:latest", "-f", "local/Dockerfile", "."]

[tasks.build-consumer-api]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/consumer-api:latest", "-f", "consumer-api/Dockerfile", "."]

[tasks.build-apps]
command = "docker"
args = ["build", "-t", "ghcr.io/0xintuition/apps:latest", "-f", "Dockerfile", "."]
