apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: decoded-consumer
  name: decoded-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: decoded-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: decoded-consumer
    spec:
      containers:
        - args:
            - ./consumer
            - --mode
            - decoded
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_REGION
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: CONSUMER_METRICS_API_PORT
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CONSUMER_METRICS_API_PORT
            - name: CONSUMER_TYPE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: CONSUMER_TYPE
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DATABASE_URL
            - name: DECODED_LOGS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DECODED_LOGS_QUEUE_URL
            - name: INTUITION_CONTRACT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: INTUITION_CONTRACT_ADDRESS
            - name: LOCALSTACK_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: LOCALSTACK_URL
            - name: RESOLVER_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RESOLVER_QUEUE_URL
            - name: RPC_URL_BASE_MAINNET
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RPC_URL_BASE_MAINNET
            - name: RUST_LOG
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: RUST_LOG
          image: ghcr.io/0xintuition/consumer:latest
          imagePullPolicy: Always
          name: decoded-consumer
          ports:
            - containerPort: 3002
              protocol: TCP
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: "2000m"
              memory: "128Mi"
            limits:
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: decoded-logs
          persistentVolumeClaim:
            claimName: decoded-logs
    