apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: envio-indexer
  name: envio-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envio-indexer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: envio-indexer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - --network
            - base-sepolia
          image: ghcr.io/0xintuition/envio-indexer:1.0.27
          imagePullPolicy: Always
          name: envio-indexer
          volumeMounts:
            - mountPath: /var/lib/data
              name: envio-indexer-data
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: envio-indexer-aws-secrets
      restartPolicy: Always
      volumes:
        - name: envio-indexer-data
          persistentVolumeClaim:
            claimName: envio-indexer-data
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: envio-indexer-aws-secrets
