apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/raw
  - secret-provider.yaml

namePrefix: "prod-linea-mainnet-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: raw-consumer


commonLabels:
  network: linea-mainnet