apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prod-base-mainnet-v2-raw-consumer-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "new-be-secrets-prod-base-mainnet-v2"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "CONSUMER_TYPE"
            objectAlias: "CONSUMER_TYPE"
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "DECODED_LOGS_QUEUE_URL"
            objectAlias: "DECODED_LOGS_QUEUE_URL"
          - path: "INDEXING_SOURCE"
            objectAlias: "INDEXING_SOURCE"
          - path: "RAW_CONSUMER_QUEUE_URL"
            objectAlias: "RAW_CONSUMER_QUEUE_URL"
          - path: "RPC_URL_BASE"
            objectAlias: "RPC_URL_BASE"
          - path: "RPC_URL_MAINNET"
            objectAlias: "RPC_URL_MAINNET"
          - path: "BACKEND_SCHEMA"
            objectAlias: "BACKEND_SCHEMA"
  secretObjects:
    - secretName: "prod-base-mainnet-v2-raw-consumer-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "CONSUMER_TYPE"
          key: "CONSUMER_TYPE"
        - objectName: "DATABASE_URL"
          key: "DATABASE_URL"
        - objectName: "DECODED_LOGS_QUEUE_URL"
          key: "DECODED_LOGS_QUEUE_URL"
        - objectName: "INDEXING_SOURCE"
          key: "INDEXING_SOURCE"
        - objectName: "RAW_CONSUMER_QUEUE_URL"
          key: "RAW_CONSUMER_QUEUE_URL"
        - objectName: "RPC_URL_BASE"
          key: "RPC_URL_BASE"
        - objectName: "RPC_URL_MAINNET"
          key: "RPC_URL_MAINNET"
        - objectName: "BACKEND_SCHEMA"
          key: "BACKEND_SCHEMA"
