apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespacedapps
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - list:
        elements:
          - cluster: prod-eks
            server: 'https://kubernetes.default.svc'
            revision: francois/add-iac
            namespace: v2-0-0
  template:
    metadata:
      name: '{{ cluster }}-namespacedapps-{{namespace}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.;/devops/argocd'
    spec:
      project: default
      source:
        repoURL: ssh://git@github.com/0xintuition/intuition-rs.git
        path: devops/argocd/namespacedapps
        targetRevision: '{{ revision }}'
        kustomize: {}
      destination:
        server: '{{ url }}'
        namespace: '{{ namespace }}'
