apiVersion: apps/v1
kind: Deployment
metadata:
  name: substreams-sink
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: substreams-sink
          image: ghcr.io/0xintuition/substreams-sink:1.0.45
          imagePullPolicy: Always 
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: substreams-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "dev-base-substreams-aws-secrets"