apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: resolver-consumer
  name: resolver-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: resolver-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: resolver-consumer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - ./consumer
            - --mode
            - resolver
          envFrom:
            - secretRef:
                name: resolver-aws-secrets
          image: ghcr.io/0xintuition/consumer:latest
          imagePullPolicy: Always
          name: resolver-consumer
          ports:
            - containerPort: 8001
              protocol: TCP
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
            - mountPath: /var/log/app
              name: resolver-logs
      restartPolicy: Always
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: resolver-aws-secrets
        - name: resolver-logs
          persistentVolumeClaim:
            claimName: resolver-logs
