apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescale-db-vectorizer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: timescale-db-vectorizer
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-base-mainnet-v-1-5-vector-aws-secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-base-mainnet-v-1-5-vector-aws-secrets"
