apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: timescale-db-vectorizer-secrets
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "prod-base-mainnet-v-1-5-vector"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: PGAI_VECTORIZER_WORKER_DB_URL
            objectAlias: PGAI_VECTORIZER_WORKER_DB_URL
          - path: OPENAI_API_KEY
            objectAlias: OPENAI_API_KEY
  secretObjects:
    - secretName: "timescale-db-vectorizer-secrets"
      type: Opaque
      data:
        - objectName: PGAI_VECTORIZER_WORKER_DB_URL
          key: PGAI_VECTORIZER_WORKER_DB_URL
        - objectName: OPENAI_API_KEY
          key: OPENAI_API_KEY
