apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ipfs-upload-consumer
  name: ipfs-upload-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: ipfs-upload-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ipfs-upload-consumer
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - args:
            - ./consumer
            - --mode
            - ipfs-upload
          envFrom:
            - secretRef:
                name: ipfs-upload-aws-secrets
          image: ghcr.io/0xintuition/consumer:latest
          imagePullPolicy: Always
          name: ipfs-upload-consumer
          ports:
            - containerPort: 8002
              protocol: TCP
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets"
              readOnly: true
            - name: ipfs-upload-logs
              mountPath: /logs
              readOnly: false
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: ipfs-upload-aws-secrets
        - name: ipfs-upload-logs
          persistentVolumeClaim:
            claimName: ipfs-upload-logs
