apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kompose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: histocrawler
  name: histocrawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: histocrawler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kompose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: histocrawler
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: histocrawler
          volumeMounts:
            - mountPath: /var/lib/data
              name: histocrawler-data
      restartPolicy: Always
      volumes:
        - name: histocrawler-data
          persistentVolumeClaim:
            claimName: histocrawler-data
