apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: histocrawler-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-immediate
  resources:
    requests:
      storage: 1Gi 