apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: sqs
  name: sqs
spec:
  type: ClusterIP
  ports:
    - name: sqs-main
      port: 4566
      targetPort: 4566
    - name: sqs-alt
      port: 4571
      targetPort: 4571
  selector:
    io.kompose.service: sqs
