-- Down migration for consolidated indexes
-- This will drop all indexes

-- Drop concurrent indexes first
DROP INDEX CONCURRENTLY IF EXISTS idx_account_id;
DROP INDEX CONCURRENTLY IF EXISTS idx_atom_value_id;
DROP INDEX CONCURRENTLY IF EXISTS idx_vault_term_curve;
DROP INDEX CONCURRENTLY IF EXISTS idx_position_account_term;
DROP INDEX CONCURRENTLY IF EXISTS idx_position_term_account;
DROP INDEX CONCURRENTLY IF EXISTS idx_triples_predicate_object;
DROP INDEX CONCURRENTLY IF EXISTS idx_triples_subject_predicate;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_creator_created_at;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_type_created_at;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_term_id;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_creator_id;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_type;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_updated_at;
DROP INDEX CONCURRENTLY IF EXISTS idx_atoms_created_at;

-- Drop regular indexes
DROP INDEX IF EXISTS idx_failed_logs_block_timestamp;
DROP INDEX IF EXISTS idx_failed_logs_address;
DROP INDEX IF EXISTS idx_failed_logs_transaction_hash;
DROP INDEX IF EXISTS idx_failed_logs_block_number;
DROP INDEX IF EXISTS idx_initialize_transaction_hash;
DROP INDEX IF EXISTS idx_initialize_block_number;
DROP INDEX IF EXISTS idx_share_price_change_term_log_index;
DROP INDEX IF EXISTS idx_share_price_change_term_transaction_hash;
DROP INDEX IF EXISTS idx_share_price_change_term_block_number;
DROP INDEX IF EXISTS idx_share_price_change_term_updated_at;
DROP INDEX IF EXISTS idx_share_price_change_updated_at;
DROP INDEX IF EXISTS idx_share_price_change_curve_id;
DROP INDEX IF EXISTS idx_triple_term_updated_at;
DROP INDEX IF EXISTS idx_triple_term_total_market_cap;
DROP INDEX IF EXISTS idx_triple_term_total_assets;
DROP INDEX IF EXISTS idx_triple_term_counter_term_id;
DROP INDEX IF EXISTS idx_triple_term_term_id;
DROP INDEX IF EXISTS idx_triple_vault_updated_at;
DROP INDEX IF EXISTS idx_triple_vault_log_index;
DROP INDEX IF EXISTS idx_triple_vault_block_number;
DROP INDEX IF EXISTS idx_triple_vault_market_cap;
DROP INDEX IF EXISTS idx_triple_vault_position_count;
DROP INDEX IF EXISTS idx_triple_vault_total_assets;
DROP INDEX IF EXISTS idx_triple_vault_total_shares;
DROP INDEX IF EXISTS idx_triple_vault_curve_id;
DROP INDEX IF EXISTS idx_triple_vault_counter_term_id;
DROP INDEX IF EXISTS idx_triple_vault_term_id;
DROP INDEX IF EXISTS idx_vault_market_cap;
DROP INDEX IF EXISTS idx_vault_total_assets;
DROP INDEX IF EXISTS idx_curve_id;
DROP INDEX IF EXISTS idx_vault_term_id;
DROP INDEX IF EXISTS idx_total_assets;
DROP INDEX IF EXISTS idx_total_market_cap;
DROP INDEX IF EXISTS idx_term_triple_id;
DROP INDEX IF EXISTS idx_term_atom_id;
DROP INDEX IF EXISTS idx_term_type;
DROP INDEX IF EXISTS idx_term_id;
DROP INDEX IF EXISTS idx_event_transaction_hash;
DROP INDEX IF EXISTS idx_event_created_at;
DROP INDEX IF EXISTS idx_event_block_number;
DROP INDEX IF EXISTS idx_event_triple;
DROP INDEX IF EXISTS idx_event_atom;
DROP INDEX IF EXISTS idx_event_type;
DROP INDEX IF EXISTS idx_organization_url;
DROP INDEX IF EXISTS idx_organization_description;
DROP INDEX IF EXISTS idx_organization_name;
DROP INDEX IF EXISTS idx_person_url;
DROP INDEX IF EXISTS idx_person_description;
DROP INDEX IF EXISTS idx_person_name;
DROP INDEX IF EXISTS idx_thing_url;
DROP INDEX IF EXISTS idx_thing_description;
DROP INDEX IF EXISTS idx_thing_name;
DROP INDEX IF EXISTS idx_atom_value_book;
DROP INDEX IF EXISTS idx_atom_value_organization;
DROP INDEX IF EXISTS idx_atom_value_person;
DROP INDEX IF EXISTS idx_atom_value_thing;
DROP INDEX IF EXISTS idx_atom_value_atom;
DROP INDEX IF EXISTS idx_signal_created_at;
DROP INDEX IF EXISTS idx_signal_triple;
DROP INDEX IF EXISTS idx_signal_atom;
DROP INDEX IF EXISTS idx_signal_account;
DROP INDEX IF EXISTS idx_predicate_object_object;
DROP INDEX IF EXISTS idx_predicate_object_predicate;
DROP INDEX IF EXISTS idx_position_vault;
DROP INDEX IF EXISTS idx_position_account;
DROP INDEX IF EXISTS idx_redemption_vault;
DROP INDEX IF EXISTS idx_redemption_receiver;
DROP INDEX IF EXISTS idx_redemption_sender;
DROP INDEX IF EXISTS idx_deposit_vault;
DROP INDEX IF EXISTS idx_deposit_receiver;
DROP INDEX IF EXISTS idx_deposit_sender;
DROP INDEX IF EXISTS idx_fee_transfer_receiver;
DROP INDEX IF EXISTS idx_fee_transfer_sender;
DROP INDEX IF EXISTS idx_vault_triple;
DROP INDEX IF EXISTS idx_vault_atom;
DROP INDEX IF EXISTS idx_triple_object;
DROP INDEX IF EXISTS idx_triple_predicate;
DROP INDEX IF EXISTS idx_triple_subject;
DROP INDEX IF EXISTS idx_triple_creator;
DROP INDEX IF EXISTS idx_atom_vault;
DROP INDEX IF EXISTS idx_atom_creator;
DROP INDEX IF EXISTS position_transaction_index_idx;
DROP INDEX IF EXISTS position_transaction_hash_idx;
DROP INDEX IF EXISTS position_log_index_idx;
DROP INDEX IF EXISTS position_block_number_idx;
DROP INDEX IF EXISTS position_shares_idx;
DROP INDEX IF EXISTS position_account_vault_idx;
DROP INDEX IF EXISTS redemption_created_at_idx;
DROP INDEX IF EXISTS redemption_log_index_idx;
DROP INDEX IF EXISTS redemption_block_number_idx;
DROP INDEX IF EXISTS deposit_created_at_idx;
DROP INDEX IF EXISTS deposit_is_atom_wallet_idx;
DROP INDEX IF EXISTS deposit_is_triple_idx;
DROP INDEX IF EXISTS deposit_log_index_idx;
DROP INDEX IF EXISTS deposit_block_number_idx;
DROP INDEX IF EXISTS fee_transfer_created_at_idx;
DROP INDEX IF EXISTS fee_transfer_block_number_idx;
DROP INDEX IF EXISTS vault_updated_at_idx;
DROP INDEX IF EXISTS vault_created_at_idx;
DROP INDEX IF EXISTS vault_total_shares_idx;
DROP INDEX IF EXISTS vault_position_count_idx;
DROP INDEX IF EXISTS vault_current_share_price_idx;
DROP INDEX IF EXISTS vault_log_index_idx;
DROP INDEX IF EXISTS vault_block_number_idx;
DROP INDEX IF EXISTS atom_log_index_idx;
