apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dev-api-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "new-be-secrets"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "CLASSIFICATION_API_PORT"
            objectAlias: "CLASSIFICATION_API_PORT"
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
          - path: "HF_TOKEN"
            objectAlias: "HF_TOKEN"
          - path: "IPFS_GATEWAY_URL"
            objectAlias: "IPFS_GATEWAY_URL"
          - path: "IPFS_UPLOAD_URL"
            objectAlias: "IPFS_UPLOAD_URL"
          - path: "PINATA_API_JWT"
            objectAlias: "PINATA_API_JWT"
          - path: "FLAG_LOCAL_WITH_CLASSIFICATION"
            objectAlias: "FLAG_LOCAL_WITH_CLASSIFICATION"
          - path: "BACKEND_SCHEMA"
            objectAlias: "BE_SCHEMA"
  secretObjects:
    - secretName: "dev-api-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "CLASSIFICATION_API_PORT"
          key: "CLASSIFICATION_API_PORT"
        - objectName: "DATABASE_URL"
          key: "DATABASE_URL"
        - objectName: "HF_TOKEN"
          key: "HF_TOKEN"
        - objectName: "IPFS_GATEWAY_URL"
          key: "IPFS_GATEWAY_URL"
        - objectName: "IPFS_UPLOAD_URL"
          key: "IPFS_UPLOAD_URL"
        - objectName: "PINATA_API_JWT"
          key: "PINATA_API_JWT"
        - objectName: "FLAG_LOCAL_WITH_CLASSIFICATION"
          key: "FLAG_LOCAL_WITH_CLASSIFICATION"
        - objectName: "BE_SCHEMA"
          key: "BE_SCHEMA"
