apiVersion: apps/v1
kind: Deployment
metadata:
  name: histocrawler
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: histocrawler
          image: ghcr.io/0xintuition/histocrawler:2.0.6
          imagePullPolicy: Always
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: prod-linea-histocrawler
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "prod-linea-mainnet-prod-linea-histocrawler"