apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: api
          image: ghcr.io/0xintuition/image-guard:1.0.27
          imagePullPolicy: Always 
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets"
            readOnly: true
          envFrom:
            - secretRef:
                name: api-aws-secrets
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "api-aws-secrets"
      
