apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret-provider.yaml

namePrefix: "dev-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: rpc-proxy

commonLabels:
  network: base-sepolia