apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescale-db-vectorizer
spec:
  template:
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: timescale-db-vectorizer
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets"
              readOnly: true
          envFrom:
            - secretRef:
                name: vectorizer-worker-secret
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "vectorizer-worker-secret"
