apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization

resources:
  - deployment.yaml
  - migrations-deployment.yaml
  - migrations-pod.yaml
  - service.yaml
  - service-account.yaml
  - secret-provider.yaml
  
commonLabels:
  component: graphql 