apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "new-be-secrets"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "HASURA_GRAPHQL_ADMIN_SECRET"
            objectAlias: "HASURA_GRAPHQL_ADMIN_SECRET"
          - path: "PINATA_AUTH"
            objectAlias: "PINATA_AUTH"
          - path: "HASURA_GRAPHQL_ENDPOINT"
            objectAlias: "HASURA_GRAPHQL_ENDPOINT"
          - path: "HASURA_GRAPHQL_METADATA_DATABASE_URL"
            objectAlias: "HASURA_GRAPHQL_METADATA_DATABASE_URL"
