apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prod-base-sepolia-prod-histoflux-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "us-west-2"
    objects: |
      - objectName: "new-be-secrets-prod-base-sepolia"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "INDEXER_DATABASE_URL"
            objectAlias: "INDEXER_DATABASE_URL"
          - path: "HISTOFLUX_CURSOR_ID"
            objectAlias: "HISTOFLUX_CURSOR_ID"
          - path: "RAW_LOGS_CHANNEL"
            objectAlias: "RAW_LOGS_CHANNEL"
          - path: "INDEXER_SCHEMA"
            objectAlias: "INDEXER_SCHEMA"
  secretObjects:
    - secretName: "prod-base-sepolia-prod-histoflux-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "INDEXER_DATABASE_URL"
          key: "INDEXER_DATABASE_URL"
        - objectName: "HISTOFLUX_CURSOR_ID"
          key: "HISTOFLUX_CURSOR_ID"
        - objectName: "RAW_LOGS_CHANNEL"
          key: "RAW_LOGS_CHANNEL"
        - objectName: "INDEXER_SCHEMA"
          key: "INDEXER_SCHEMA"
