apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prod-sepolia-substreams-aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "new-be-secrets-prod-base-sepolia"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
        jmesPath:
          - path: "AWS_ACCESS_KEY_ID"
            objectAlias: "AWS_ACCESS_KEY_ID"
          - path: "AWS_SECRET_ACCESS_KEY"
            objectAlias: "AWS_SECRET_ACCESS_KEY"
          - path: "AWS_REGION"
            objectAlias: "AWS_REGION"
          - path: "INDEXER_DATABASE_URL"
            objectAlias: "INDEXER_DATABASE_URL"
          - path: "RAW_CONSUMER_QUEUE_URL"
            objectAlias: "RAW_CONSUMER_QUEUE_URL"
          - path: "SUBSTREAMS_ENDPOINT"
            objectAlias: "SUBSTREAMS_ENDPOINT"
          - path: "SUBSTREAMS_PACKAGE"
            objectAlias: "SUBSTREAMS_PACKAGE"
          - path: "SUBSTREAMS_MODULE"
            objectAlias: "SUBSTREAMS_MODULE"
          - path: "SUBSTREAMS_START_BLOCK"
            objectAlias: "SUBSTREAMS_START_BLOCK"
          - path: "SUBSTREAMS_API_TOKEN"
            objectAlias: "SUBSTREAMS_API_TOKEN"
          - path: "INDEXER_SCHEMA"
            objectAlias: "INDEXER_SCHEMA"
          - path: "INTUITION_CONTRACT_ADDRESS"
            objectAlias: "INTUITION_CONTRACT_ADDRESS"
          - path: "SUBSTREAMS_OUTPUT"
            objectAlias: "SUBSTREAMS_OUTPUT"
  secretObjects:
    - secretName: "prod-sepolia-substreams-aws-secrets"  # The name of the Kubernetes secret to create
      type: Opaque
      data:
        - objectName: "AWS_ACCESS_KEY_ID"
          key: "AWS_ACCESS_KEY_ID"
        - objectName: "AWS_SECRET_ACCESS_KEY"
          key: "AWS_SECRET_ACCESS_KEY"
        - objectName: "AWS_REGION"
          key: "AWS_REGION"
        - objectName: "INDEXER_DATABASE_URL"
          key: "INDEXER_DATABASE_URL"
        - objectName: "RAW_CONSUMER_QUEUE_URL"
          key: "RAW_CONSUMER_QUEUE_URL"
        - objectName: "SUBSTREAMS_ENDPOINT"
          key: "SUBSTREAMS_ENDPOINT"
        - objectName: "SUBSTREAMS_PACKAGE"
          key: "SUBSTREAMS_PACKAGE"
        - objectName: "SUBSTREAMS_MODULE"
          key: "SUBSTREAMS_MODULE"
        - objectName: "SUBSTREAMS_START_BLOCK"
          key: "SUBSTREAMS_START_BLOCK"
        - objectName: "SUBSTREAMS_API_TOKEN"
          key: "SUBSTREAMS_API_TOKEN"
        - objectName: "INDEXER_SCHEMA"
          key: "INDEXER_SCHEMA"
        - objectName: "INTUITION_CONTRACT_ADDRESS"
          key: "INTUITION_CONTRACT_ADDRESS"
        - objectName: "SUBSTREAMS_OUTPUT"
          key: "SUBSTREAMS_OUTPUT"