apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: api
          ports:
          - containerPort: 3000
            protocol: TCP
          envFrom: []
          env:
            - name: CLASSIFICATION_API_PORT
              value: "3000"
            - name: IPFS_GATEWAY_URL
              value: "http://ipfs:8080"
            - name: IPFS_UPLOAD_URL
              value: "http://ipfs:5001"
            - name: FLAG_LOCAL_WITH_CLASSIFICATION
              value: "true"
            - name: BE_SCHEMA
              value: "public"

