apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      serviceAccountName: secrets-access-sa
      containers:
        - name: api
          ports:
          - containerPort: 3000
            protocol: TCP
      
