apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ipfs-upload
  - secret-provider.yaml
  - pvc.yaml

namePrefix: "prod-base-mainnet-v2-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: ipfs-upload-consumer

commonLabels:
  network: base-mainnet