apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/resolver
  - secret-provider.yaml

namePrefix: "prod-base-sepolia-" 

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: resolver-consumer

commonLabels:
  network: base-sepolia