[package]
name = "envio-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
aws-config.workspace = true
aws-sdk-sqs.workspace = true
aws-smithy-runtime-api.workspace = true
env_logger.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
models = { path = "../models" }
hypersync-client.workspace = true
thiserror.workspace = true
url.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
clap.workspace = true
envy.workspace = true
log.workspace = true