apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-base-mainnet-resolver-logs
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi