apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-rpc-proxy
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: 'https://github.com/0xintuition/intuition-rs.git'
    targetRevision: HEAD
    path: devops/aws/rpc-proxy/overlays/dev
    kustomize:
      patches:
        - target:
            kind: Deployment
            name: rpc-proxy
          patch: |-
            - op: replace
              path: /spec/template/spec/serviceAccountName
              value: prod-eks-secrets-access-sa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
