apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/decoded
  - secret-provider.yaml


patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: decoded-consumer

commonLabels:
  network: base-sepolia